### ISSUE TITLE
Access denied for /var/run/docker.sock

### ISSUE THREAD

**Issue by tesYolan** [tesYolan/Restforhead#35]
When creating new instance, creation of new instances fails with the following command: 
```
node_1     | [0] error: error creating container
node_1     | [0] error: get's to error
node_1     | [0] error:  Error: connect EACCES /var/run/docker.sock
node_1     | [0]     at Object._errnoException (util.js:1022:11)
node_1     | [0]     at _exceptionWithHostPort (util.js:1044:20)
node_1     | [0]     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```
This is permission issue to allow the creation of sister/brother containers form within the container. This requires that permission for /var/run/docker.sock be allowed for node application. This needs to be indicated in the README.md.

**Comment by tesYolan** [comment]
Have tried numerous alternatives ranging from making docker group id consistent from within container and host. (from https://stackoverflow.com/questions/36185035/how-to-mount-docker-socket-as-volume-in-docker-container-with-correct-group). 

One could utilize http path to enable docker communication which could be nice.

**Comment by tesYolan** [comment]
Run the following before mounting the volume. 
```sudo chmod 777 /var/run/docker.sock```

**Comment by heithemmoumni** [comment]
check this link
https://docs.docker.com/install/linux/linux-postinstall/

**Comment by johnkennyuk** [comment]
> Run the following before mounting the volume.
> `sudo chmod 777 /var/run/docker.sock`

This works everytime!!

Thanks for this....
